--  AEROMEXICO
DROP DATABASE IF EXISTS aeromexico;
CREATE DATABASE aeromexico;

USE aeromexico;

CREATE TABLE CLIENTE(
	IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
    IDPASAJERO INT,
    IDTICKET INT,
    IDVUELO INT,
    IDEMPLEADO INT,
    IDCARRY INT,
    FECHA DATETIME
);
CREATE TABLE PASAJERO(
	IDPASAJERO		INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE			VARCHAR(100),
    APELLIDO		VARCHAR(100),
    CORREO			VARCHAR(100),
    TELEFONO 		VARCHAR(100),
    TIPO_CLIENTE 	VARCHAR(100)
);
CREATE TABLE VUELO(
	IDVUELO				INT PRIMARY KEY AUTO_INCREMENT,
    IDTICKET			INT,
    DESTINO				VARCHAR(100),
    NUMERO_VUELO		INT
);
CREATE TABLE TICKET(
	IDTICKET		INT PRIMARY KEY AUTO_INCREMENT,
    COSTO			DECIMAL(50,2),
    ASIENTO			INT,
    PUERTA_ABORDAJE	INT

);
CREATE TABLE EMPLEADO(
	IDEMPLEADO	 	INT PRIMARY KEY AUTO_INCREMENT,
    IDPASAJERO		INT,
    NOMBRE			VARCHAR(100),
    DIRECCION 		VARCHAR(100),
    TELEFONO 		VARCHAR(100)
);
CREATE TABLE CARRY(
	IDCARRY 		INT PRIMARY KEY AUTO_INCREMENT,
    TIPO_MALETA		BOOLEAN,
    DOCUMENTADA		BOOLEAN
);

-- FK
-- VUELO

ALTER TABLE VUELO
	ADD CONSTRAINT FK_VUELO_TICKET
    FOREIGN KEY (IDTICKET) REFERENCES TICKET(IDTICKET)
;

-- EMPLEADO

ALTER TABLE EMPLEADO
	ADD CONSTRAINT FK_EMPLEADO_PASAJERO
    FOREIGN KEY (IDPASAJERO) REFERENCES PASAJERO(IDPASAJERO)
;

-- CLIENTE

ALTER TABLE CLIENTE
	ADD CONSTRAINT FK_CLIENTE_PASAJERO
    FOREIGN KEY (IDPASAJERO) REFERENCES PASAJERO(IDPASAJERO)
;

ALTER TABLE CLIENTE
	ADD CONSTRAINT FK_CLIENTE_TICKET
    FOREIGN KEY (IDTICKET) REFERENCES TICKET(IDTICKET)
;

ALTER TABLE CLIENTE
	ADD CONSTRAINT FK_CLIENTE_VUELO
    FOREIGN KEY (IDVUELO) REFERENCES VUELO(IDVUELO)
;

ALTER TABLE CLIENTE
	ADD CONSTRAINT FK_CLIENTE_EMPLEADO
    FOREIGN KEY (IDEMPLEADO) REFERENCES EMPLEADO(IDEMPLEADO)
;

ALTER TABLE CLIENTE
	ADD CONSTRAINT FK_CLIENTE_CARRY
    FOREIGN KEY (IDCARRY) REFERENCES CARRY(IDCARRY)
;