DROP DATABASE IF EXISTS aeromexico;

CREATE DATABASE aeromexico;

USE aeromexico;

CREATE TABLE CLIENTE(
	IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
    IDPASAJERO INT,
    IDTICKET INT,
    IDVUELO INT,
    IDEMPLEADO INT,
    IDCARRY INT,
	NOMBRE			VARCHAR(100),
    APELLIDO		VARCHAR(100),
    CORREO			VARCHAR(100),
    TELEFONO 		VARCHAR(100),
    FECHA DATETIME DEFAULT (CURRENT_TIMESTAMP)
);
CREATE TABLE PASAJERO(
	IDPASAJERO		INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE			VARCHAR(100),
    APELLIDO		VARCHAR(100),
    CORREO			VARCHAR(100),
    TELEFONO 		VARCHAR(100),
    TIPO_CLIENTE 	VARCHAR(100)
);
CREATE TABLE VUELO(
	IDVUELO				INT PRIMARY KEY AUTO_INCREMENT,
    IDTICKET			int,
    DESTINO				VARCHAR(100),
    NUMERO_VUELO		VARCHAR(100)
);
CREATE TABLE TICKET(
	IDTICKET		INT PRIMARY KEY AUTO_INCREMENT,
    COSTO			DECIMAL(50,2),
    ASIENTO			VARCHAR(100),
    PUERTA_ABORDAJE	VARCHAR(100)

);
CREATE TABLE EMPLEADO(
	IDEMPLEADO	 	INT PRIMARY KEY AUTO_INCREMENT,
    IDPASAJERO		INT,
    NOMBRE			VARCHAR(100),
    DIRECCION 		VARCHAR(100),
    TELEFONO 		VARCHAR(100)
);
CREATE TABLE CARRY(
	IDCARRY 		INT PRIMARY KEY AUTO_INCREMENT,
    TIPO_MALETA		boolean,
    DOCUMENTADA		boolean
);

-- FK
-- VUELO

ALTER TABLE VUELO
	ADD CONSTRAINT FK_VUELO_TICKET
    FOREIGN KEY (IDTICKET) REFERENCES TICKET(IDTICKET)
;

-- EMPLEADO

ALTER TABLE EMPLEADO
	ADD CONSTRAINT FK_EMPLEADO_PASAJERO
    FOREIGN KEY (IDPASAJERO) REFERENCES PASAJERO(IDPASAJERO)
;

-- CLIENTE

ALTER TABLE CLIENTE
	ADD CONSTRAINT FK_CLIENTE_PASAJERO
    FOREIGN KEY (IDPASAJERO) REFERENCES PASAJERO(IDPASAJERO)
;

ALTER TABLE CLIENTE
	ADD CONSTRAINT FK_CLIENTE_TICKET
    FOREIGN KEY (IDTICKET) REFERENCES TICKET(IDTICKET)
;

ALTER TABLE CLIENTE
	ADD CONSTRAINT FK_CLIENTE_VUELO
    FOREIGN KEY (IDVUELO) REFERENCES VUELO(IDVUELO)
;

ALTER TABLE CLIENTE
	ADD CONSTRAINT FK_CLIENTE_EMPLEADO
    FOREIGN KEY (IDEMPLEADO) REFERENCES EMPLEADO(IDEMPLEADO)
;

ALTER TABLE CLIENTE
	ADD CONSTRAINT FK_CLIENTE_CARRY
    FOREIGN KEY (IDCARRY) REFERENCES CARRY(IDCARRY)
;

select * from cliente;

 -- Se insertan los datos a la tabla
 
 INSERT INTO CLIENTE
 (FECHA)
 VALUES
(01-01-2024),
(01-01-2024),
(01-01-2024),
(01-01-2024),
(01-01-2024);

 INSERT INTO PASAJERO
 (NOMBRE, APELLIDO, CORREO, TELEFONO, TIPO_CLIENTE)
 VALUES
('Daniela','Hernandez','daniela@gmail.com','5591966557','Aeromexico Rewards'),
('Alejandro','Sosa','alejandro@gmail.com','5527720655','Aeromexico AMEX'),
('Jesus','Lopez','jesus@gmail.com','5514253658','Aeromexico Santander'),
('Bruno','Rufino','bruno@gmail.com','5518598463','Aeromexico Santander'),
('Karla','Soto','karla@gmail.com','5512785941','Aeromexico Rewards');

select * from PASAJERO;


 INSERT INTO VUELO
 (DESTINO, NUMERO_VUELO)
 VALUES
('Toronto','VU001'),
('Cancun','VU002'),
('Bogota','VU003'),
('Monterrey','VU004'),
('Gudalajara','VU005');

select * from VUELO;

 INSERT INTO TICKET
 (COSTO, ASIENTO, PUERTA_ABORDAJE)
 VALUES
(5000,'AS001','14'),
(4000,'AS002','12'),
(1500,'AS003','23'),
(1000,'AS004','21'),
(2500,'AS005','11');

select * from TICKET;

  INSERT INTO EMPLEADO
 (NOMBRE, DIRECCION, TELEFONO)
 VALUES
('Daniela','ciudad de mexico','5591966557'),
('Alejandro','playa del carmen','5527720655'),
('Jesus','xalapa','5514253658'),
('Bruno','merida','5518598463'),
('Karla','cancun','5512785941');
 
 select * from EMPLEADO;
 
  INSERT INTO CARRY
(TIPO_MALETA, DOCUMENTADA)
 VALUES
 (true,true),
(false,true),
(false,false),
(true,true),
(true,false);

select * from CARRY;